[package]
name = "trilogy-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
num = "0.4.0"
trilogy-vm-derive = { path = "../trilogy-vm-derive/" }
