[workspace]
resolver = "2"
members = [
    "trilogy",
    "trilogy-scanner",
    "trilogy-parser",
    "trilogy-parser-derive",
    "trilogy-loader",
    "trilogy-ir",
    "trilogy-codegen",
    "trilogy-vm",
    "trilogy-vm-derive",
    "trilogy-derive",
]
