[workspace]
resolver = "2"
members = [
    "trilogy",
    "trilogy-derive",
    "trilogy-scanner",
    "trilogy-parser",
    "trilogy-parser-derive",
    "trilogy-ir",
    "trilogy-codegen",
    "trilogy-vm",
    "trilogy-vm-derive",
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"

[profile.perf]
inherits = "release"
codegen-units = 16
lto = false
