[workspace]
members = [
    "trilogy",
    "trilogy-scanner",
    "trilogy-parser",
    "trilogy-parser-derive",
    "trilogy-analyzer",
    "trilogy-loader",
    "trilogy-lexical-ir",
    "trilogy-vm",
]
