use crate::{Builder, Cache, Location};

pub(crate) fn apply<C>(builder: Builder<C>) -> Builder<C>
where
    C: Cache,
{
    builder
        .source_module(
            Location::library("io").unwrap(),
            include_str!("./io.tri").to_owned(),
        )
        .source_module(
            Location::library("debug").unwrap(),
            include_str!("./debug.tri").to_owned(),
        )
        .source_module(
            Location::library("atom").unwrap(),
            include_str!("./atom.tri").to_owned(),
        )
        .source_module(
            Location::library("string").unwrap(),
            include_str!("./string.tri").to_owned(),
        )
        .source_module(
            Location::library("number").unwrap(),
            include_str!("./number.tri").to_owned(),
        )
        .source_module(
            Location::library("iterator").unwrap(),
            include_str!("./iterator.tri").to_owned(),
        )
        .source_module(
            Location::library("array").unwrap(),
            include_str!("./array.tri").to_owned(),
        )
        .source_module(
            Location::library("set").unwrap(),
            include_str!("./set.tri").to_owned(),
        )
        .source_module(
            Location::library("grid").unwrap(),
            include_str!("./grid.tri").to_owned(),
        )
        .source_module(
            Location::library("heap").unwrap(),
            include_str!("./heap.tri").to_owned(),
        )
        .source_module(
            Location::library("parsec").unwrap(),
            include_str!("./parsec.tri").to_owned(),
        )
        .source_module(
            Location::library("ansi").unwrap(),
            include_str!("./ansi.tri").to_owned(),
        )
        .source_module(
            Location::library("core").unwrap(),
            include_str!("./core.tri").to_owned(),
        )
}
