[package]
name = "trilogy-cps"
version = "0.1.0"
edition = "2021"

[dependencies]
trilogy-ir = { path = "../trilogy-ir/" }
trilogy-scanner = { path = "../trilogy-scanner/" }
source-span = "2.7.0"
bitvec = "1.0.1"
num = "0.4.0"

[lints]
workspace = true
