[package]
name = "trilogy-scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
peekmore = { version = "1.0.0", features = ["smallvec"] }
source-span = "2.7.0"
