[package]
name = "trilogy-scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
num = "0.4.0"
peekmore = { version = "1.0.0", features = ["smallvec"] }
source-span = "2.7.0"

[lints]
workspace = true
