name: Spec
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('spec/**/*.tex', 'spec/**/*.tri') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: tectonic -X build
        working-directory: spec
      - uses: actions/upload-artifact@v3
        with:
          name: Trilogy Language Specification
          path: spec/build/trilogy-language-specification/trilogy-language-specification.pdf
