name: Trilogy CI

on: push

jobs:
  test-llvm:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install LLVM
        run: sudo apt-get install llvm libpolly-18-dev
      - name: Install Rust
        run: |
          rustup install stable
          rustup default stable
      - name: Build
        run: cargo build --release
      - name: Run testsuite
        run: |
          ./testsuite-llvm/test.sh -n -r
