name: Trilogy CI

on: push

jobs:
  stdlib:
    name: stdlib
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - 32bit
          - 64bit
          - multithread
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        run: |
          rustup install stable
          rustup default stable
      - name: Build
        run: cargo build --features ${{ matrix.features }} --release
      - name: Run stdlib tests
        run: |
          ls ./trilogy/src/stdlib/*.tri | xargs -I _ ./target/release/trilogy test _
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - 32bit
          - 64bit
          - multithread
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        run: |
          rustup install stable
          rustup default stable
      - name: Build
        run: cargo build --features ${{ matrix.features }} --release
      - name: Run testsuite
        run: |
          ls ./testsuite/*/*.tri | xargs -I _ ./target/release/trilogy test _
